title: Chasun's Blog
description: Wrote some tech articles in daily work.
show_downloads: false

baseurl: "/chasun" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://lumiaozi.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Chasun
image: /thumbnail-jumbo.png
twitter:
  username: None

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['最近动态', '关于', '联系我']
